baseURL: "https://gupta-puru.github.com/hugo-website/" 
title: Puru Gupta
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Curriculum Vitae
          url: books/
          weight: 5 
        - name: Research
          url: papers/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: Code
          url: data/
          weight: 4 
        - name: Warwick
          url: https://warwick.ac.uk/fac/soc/economics/staff/pgupta/
          weight: 6

params:
    description: "I am a PhD candidate at the Department of Economics, University of Warwick, affiliated with the Stochastic Finance research group."
    author: Puru Gupta
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Puru Gupta
          subtitle: "I am a PhD candidate at the Department of Economics, University of Warwick, affiliated with the Stochastic Finance research group. My current research focuses on endogenous liquidity frictions in financial markets dominated by large institutional investors or whales and their import for optimal risk management and asset pricing. I also explore optimal supply chain risk management through the use of derivative securities."
          imageUrl: "Puru.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Puru Gupta
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
            - name: Codes
              url: data/
            - name: CV
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Warwick
              url: https://warwick.ac.uk/fac/soc/economics/staff/pgupta/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:puru.gupta.1@warwick.ac.uk
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ZwfVefEAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/gupta-puru
        - name: Linkedin
          url: https://www.linkedin.com/in/puru-gupta-b873008a/
        - name: YouTube
          url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Puru Gupta"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
